### ISSUE TITLE
Set up network-api templates -> mezzanine template deployments

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#87]
This will rely on:
- [ ] converting pug to django templates #86 
- [ ] making template conversion part of the network-api build #88 
- [ ] sending the converted template(s) over to the mezzanine repository #89 
- [ ] have the mezzanine repo automatically put them in the right place so that auto-deploy works #90

**Comment by Pomax** [comment]
tracking on the `network` repo
