### ISSUE TITLE
Improve Authentication system

### ISSUE THREAD

**Issue by simonwex** [mozilla/network-api#92]
Related to the discussion here, figure out what our best approach is for Auth for the CMS. 

Conclusion from [this bug](https://github.com/mozilla/network-api/issues/28) is that an "opinionated nascar" (Google, Github, Facebook, etc) is the answer?

**Comment by Pomax** [comment]
first pass:
- [ ] add gauth as bare minimum login concept
second pass:
- [ ] find a good library for arbitrary social login
- [ ] add this library and set it appropriately
- [ ] test this solution

**Comment by alanmoo** [comment]
Will Google Auth be our opinionated main login system once support for arbitrary logins is added?

**Comment by Pomax** [comment]
by using the social-auth-core and social-app-django libraries, we should be able to add an arbitrary number of social logins. Google auth works as both PoC of the libraries and the first social login option with automatic user permissions set based on mozilla logins.

**Comment by Pomax** [comment]
the last step here is to make sure that users are auto-assigned the right group policy, so I'm going to write some code that looks for a group policy called "staff" and adds that to the user's policy list.

**Comment by Pomax** [comment]
we're good to go here - opening a followup issue for making sure that "staff" has the right permissions, which is a thing that either needs

**Comment by Pomax** [comment]
all the work here has been completed
